default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vinni
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: SistemaDeGerenciamento_development

test:
  <<: *default
  database: SistemaDeGerenciamento_test
  port: 5433

production:
  <<: *default
  database: SistemaDeGerenciamento_production
