default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vinni  # Substitua pelo seu usuário PostgreSQL
  password: adm123  # Substitua pela sua senha PostgreSQL
  host: localhost

development:
  <<: *default
  database: SistemaDeGerenciamento_development

test:
  <<: *default
  database: SistemaDeGerenciamento_test

production:
  <<: *default
  database: SistemaDeGerenciamento_production

actions:  
  <<: *default
  database: SistemaDeGerenciamento_actions  # Nome do banco para o ambiente actions
