default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: SistemaDeGerenciamento_development

test:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_test
  pool: 5
  username: vinni
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5433

production:
  <<: *default
  database: SistemaDeGerenciamento_production
