development:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_development
  pool: 5
  username: vinni
  password: <%= ENV['DATABASE_PASSWORD'] %> 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_test
  pool: 5
  username: vinni
  password: <%= ENV['DATABASE_PASSWORD'] %>  
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_production
  pool: 5
  username: vinni
  password: <%= ENV['DATABASE_PASSWORD'] %>  
  host: localhost
