default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vinni  # Substitua pelo seu usuário PostgreSQL
  password: adm123  # Substitua pela sua senha PostgreSQL
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_development
  pool: 5
  username: vinni
  password: adm123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_test
  pool: 5
  username: vinni
  password: adm123
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_production
  pool: 5
  username: vinni
  password: adm123
  host: localhost


actions:  
  <<: *default
  database: SistemaDeGerenciamento_actions  # Nome do banco para o ambiente actions
  username: vinni  
  password: adm123