development:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_development
  pool: 5
  username: postgres
  password: adm123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_test
  pool: 5
  username: postgres
  password: adm123
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: SistemaDeGerenciamento_production
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost