name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready -U postgres
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: SistemaDeGerenciamento_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Instalar Cliente PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Cache de Gems do Ruby
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Aguardar pelo Postgres
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres está pronto!"
              break
            fi
            echo "Aguardando pelo Postgres..."
            sleep 2
          done

      - name: Configurar Banco de Dados
        env:
          PG_DATABASE: SistemaDeGerenciamento_test
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Executar Testes
        env:
          PG_DATABASE: SistemaDeGerenciamento_test
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          bundle exec rails test